# Generated by Django 4.2.1 on 2023-05-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('approved_vacation', models.IntegerField()),
                ('available_vacation', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('martial_status', models.CharField(max_length=20)),
            ],
        ),
    ]
