# Generated by Django 4.1.9 on 2023-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_vacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacations',
            name='vacID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vacations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
