# Generated by Django 4.1.9 on 2023-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_vacations_vacid_alter_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='vacID',
            field=models.CharField(max_length=255),
        ),
    ]
